log-rotate:
  enabled: true             # 启用或禁用日志轮转
  max-size-mb: 10          # 单个日志文件的最大尺寸，单位MB
  keep-days: 7             # 保留日志的天数

ignore-commandblocks:
  - 1,1,1,world            # 忽略这个坐标的命令方块
  - 2,2,2,world            # 忽略这个坐标的命令方块
