name: CommandLogger
main: com.Tms.commandlogger.CommandLogger
version: 1.0
api-version: 1.21
author: Tms
description: Advanced command execution logger
libraries:
  - io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT